import { PropertyType } from './lib/generated/prisma/enums';

export const samplePropertiesData = [
  {
    name: 'The Oakwood Residence',
    description:
      'Experience sophisticated urban living in this stunning 2-bedroom apartment overlooking Dubai Marina. The open-plan design includes a spacious living and dining area bathed in natural light through floor-to-ceiling windows. The modern kitchen features premium built-in appliances and ample storage. Both bedrooms have generous closet space, and the master suite offers a private balcony with panoramic views. Located in the heart of the marina, you are steps away from waterfront cafés, fine dining, and leisure promenades, making this an ideal home for professionals or small families seeking style, comfort, and convenience.',
    location: 'Al Marsa Street, Dubai Marina',
    city: 'Dubai',
    price: 3500000,
    area: 1200,
    bedrooms: 2,
    bathrooms: 2,
    images: [
      '/images/properties/a1.jpg',
      '/images/properties/a2.jpg',
      '/images/properties/a3.jpg',
      '/images/properties/a4.jpg',
    ],
    isFeatured: true,
    reserveFees: 500.0,
    type: PropertyType.SALE,
    amenities: [
      'pool',
      'gym',
      'parking',
      'balcony',
      'security',
      'wifi',
      'jacuzzi',
      'barbecue',
    ],
  },
  {
    name: 'Green Haven Loft',
    description:
      'A bright and modern studio in the heart of Downtown Dubai, offering spectacular views of Burj Khalifa. The open living space maximizes functionality, featuring a compact yet well-equipped kitchen and a stylish bathroom. Large windows ensure an abundance of natural light. This studio is perfect for individuals or investors seeking a central location close to Dubai Mall, metro stations, and the city’s premier entertainment venues.',
    location: 'Mohammed Bin Rashid Boulevard, Downtown Dubai',
    city: 'Dubai',
    price: 1200000,
    area: 500,
    bedrooms: 1,
    bathrooms: 1,
    images: [
      '/images/properties/b1.jpg',
      '/images/properties/b2.jpg',
      '/images/properties/b3.jpg',
      '/images/properties/b4.jpg',
    ],
    isFeatured: true,
    reserveFees: 300.0,
    type: PropertyType.SALE,
    amenities: ['parking', 'gym', 'security', 'wifi', 'balconyView'],
  },
  {
    name: 'Skyline Heights',
    description:
      'This elegant 4-bedroom villa in Arabian Ranches offers a spacious and thoughtfully designed layout. The living and dining areas are open and welcoming, perfect for entertaining guests. Large windows throughout provide ample natural light. The villa includes multiple bathrooms with modern fixtures and a master suite with private views of the landscaped garden. Ideally located within a secure and serene community with easy access to schools, parks, and local amenities, this villa is perfect for families seeking both comfort and privacy.',
    location: 'Al Safa Street, Arabian Ranches',
    city: 'Dubai',
    price: 7800000,
    area: 3500,
    bedrooms: 4,
    bathrooms: 4,
    images: [
      '/images/properties/c1.jpg',
      '/images/properties/c2.jpg',
      '/images/properties/c3.jpg',
      '/images/properties/c4.jpg',
    ],
    isFeatured: false,
    reserveFees: 800.0,
    type: PropertyType.SALE,
    amenities: [
      'pool',
      'gym',
      'parking',
      'balcony',
      'garden',
      'security',
      'sauna',
      'petFriendly',
    ],
  },
  {
    name: 'The Modern Elm',
    description:
      'This 3-bedroom apartment in Jumeirah Beach Residence boasts sweeping views of the sea and coastline. The spacious interior includes a modern kitchen, comfortable living and dining areas, and generously sized bedrooms. Floor-to-ceiling windows allow natural light to fill every room. Located steps from the beach and local cafes, this property offers the ideal balance of seaside tranquility and urban convenience for families or individuals seeking a premium coastal lifestyle.',
    location: 'The Walk, Jumeirah Beach Residence',
    city: 'Dubai',
    price: 5200000,
    area: 1800,
    bedrooms: 3,
    bathrooms: 3,
    images: [
      '/images/properties/d1.jpg',
      '/images/properties/d2.jpg',
      '/images/properties/d3.jpg',
      '/images/properties/d4.jpg',
    ],
    isFeatured: true,
    reserveFees: 600.0,
    type: PropertyType.SALE,
    amenities: [
      'pool',
      'gym',
      'parking',
      'balcony',
      'security',
      'beachAccess',
      'wifi',
    ],
  },
  {
    name: 'Urban Crest Apartments',
    description:
      'Fully furnished 2-bedroom apartment in Business Bay, offering open-plan living with natural light throughout. Designed for short-term rental, ideal for professionals or families. Convenient access to commercial centers, restaurants, and transport makes city living effortless.',
    location: 'Marasi Drive, Business Bay',
    city: 'Dubai',
    price: 12000,
    area: 900,
    bedrooms: 2,
    bathrooms: 2,
    images: [
      '/images/properties/e1.jpg',
      '/images/properties/e2.jpg',
      '/images/properties/e3.jpg',
      '/images/properties/e4.jpg',
    ],
    isFeatured: false,
    reserveFees: 200.0,
    type: PropertyType.RENT,
    amenities: ['pool', 'gym', 'parking', 'security', 'wifi', 'balcony'],
  },
  {
    name: 'Willow Park Residences',
    description:
      'Luxury 3-bedroom penthouse on Al Reem Island, Abu Dhabi, with expansive living areas, floor-to-ceiling windows, and panoramic city and sea views. Modern kitchen, master suite with private balcony, and access to leisure facilities, cafes, and waterfront promenades.',
    location: 'Al Reem Island, Abu Dhabi',
    city: 'Abu Dhabi',
    price: 8200000,
    area: 1600,
    bedrooms: 3,
    bathrooms: 3,
    images: [
      '/images/properties/f1.jpg',
      '/images/properties/f2.jpg',
      '/images/properties/f3.jpg',
      '/images/properties/f4.jpg',
    ],
    isFeatured: false,
    reserveFees: 700.0,
    type: PropertyType.SALE,
    amenities: [
      'pool',
      'gym',
      'parking',
      'balcony',
      'security',
      'jacuzzi',
      'wifi',
      'sauna',
    ],
  },
  {
    name: 'The Maple Grove',
    description:
      '3-bedroom villa in Khalifa City, Abu Dhabi, offering open-plan living, modern kitchen, spacious bedrooms, and a serene backyard with private pool. Located in a quiet neighborhood with easy access to schools, shopping, and transport links.',
    location: 'Khalifa City, Abu Dhabi',
    city: 'Abu Dhabi',
    price: 6200000,
    area: 2800,
    bedrooms: 3,
    bathrooms: 3,
    images: [
      '/images/properties/g1.jpg',
      '/images/properties/g2.jpg',
      '/images/properties/g3.jpg',
      '/images/properties/g4.jpg',
    ],
    isFeatured: false,
    reserveFees: 600.0,
    type: PropertyType.SALE,
    amenities: ['pool', 'garden', 'parking', 'security', 'wifi', 'kidFriendly'],
  },
  {
    name: 'Sunset Boulevard Flats',
    description:
      'Stylish studio in Al Majaz, Sharjah, with functional open-plan layout, compact kitchen, bright living area, and proximity to malls, transport, and leisure facilities. Perfect for singles or young professionals.',
    location: 'Al Majaz, Sharjah',
    city: 'Sharjah',
    price: 7000,
    area: 400,
    bedrooms: 1,
    bathrooms: 1,
    images: [
      '/images/properties/h1.jpg',
      '/images/properties/h2.jpg',
      '/images/properties/h3.jpg',
      '/images/properties/h4.jpg',
    ],
    isFeatured: false,
    reserveFees: 150.0,
    type: PropertyType.RENT,
    amenities: ['parking', 'wifi', 'security', 'petFriendly', 'balconyView'],
  },
  {
    name: 'Cedar Ridge Retreat',
    description:
      'Contemporary 2-bedroom apartment in Al Nahda, Sharjah, featuring open-plan living spaces, modern kitchen, and bright bedrooms. Ideal for small families or professionals. Conveniently located near schools, shopping centers, and transport.',
    location: 'Al Nahda, Sharjah',
    city: 'Sharjah',
    price: 4800000,
    area: 1100,
    bedrooms: 2,
    bathrooms: 2,
    images: [
      '/images/properties/i1.jpg',
      '/images/properties/i2.jpg',
      '/images/properties/i3.jpg',
      '/images/properties/i4.jpg',
    ],
    isFeatured: false,
    reserveFees: 550.0,
    type: PropertyType.SALE,
    amenities: [
      'pool',
      'gym',
      'parking',
      'balcony',
      'security',
      'wifi',
      'balconyView',
    ],
  },
  {
    name: 'The Horizon Lofts',
    description:
      'A cozy 1-bedroom apartment in Al Khalidiyah, Abu Dhabi, perfect for singles or couples. The apartment offers a comfortable living area, functional kitchen, and a modern bathroom. Located within walking distance to shops, restaurants, and public transport, providing easy access to city conveniences while maintaining a quiet and friendly environment.',
    location: 'Al Khalidiyah, Abu Dhabi',
    city: 'Abu Dhabi',
    price: 9000,
    area: 500,
    bedrooms: 1,
    bathrooms: 1,
    images: [
      '/images/properties/j1.jpg',
      '/images/properties/j2.jpg',
      '/images/properties/j3.jpg',
      '/images/properties/j4.jpg',
    ],
    isFeatured: false,
    reserveFees: 200.0,
    type: PropertyType.RENT,
    amenities: ['wifi', 'parking', 'security', 'petFriendly', 'balconyView'],
  },
];
