import { PropertyList } from './lib/generated/prisma/enums';

export const samplePropertiesData = [
  {
    name: 'The Oakwood Residence',
    description:
      'Located along the vibrant waterfront of Dubai Marina, this elegant two-bedroom residence offers an exceptional balance of comfort, design, and urban convenience. The apartment features a spacious open-plan living and dining area framed by large floor-to-ceiling windows that provide natural light throughout the day and partial marina views during the evening. A contemporary kitchen with modern cabinetry and integrated appliances sits adjacent to the main living area, making the space ideal for both daily living and entertaining guests. Both bedrooms are generously sized with built-in wardrobes, while the master bedroom includes an en-suite bathroom and a private balcony overlooking the surrounding skyline. Residents enjoy immediate access to the Marina promenade, cafés, restaurants, fitness centers, and waterfront leisure activities.',
    address: 'Marina Promenade Tower A, Marina Walk, Dubai Marina',
    city: 'dubai',
    latitude: 25.086685,
    longitude: 55.146456,
    price: 3500000,
    area: 1200,
    bedrooms: 2,
    bathrooms: 2,
    images: [
      '/images/properties/a1.jpg',
      '/images/properties/a2.jpg',
      '/images/properties/a3.jpg',
      '/images/properties/a4.jpg',
    ],
    isFeatured: true,
    propertyList: PropertyList.SALE,
    propertyType: 'apartment',
    amenities: [
      'gym',
      'bbqArea',
      'smartHome',
      'rooftopTerrace',
      'jacuzzi',
      'garden',
      'privatePool',
      'sauna',
      'walkInCloset',
      'garage',
      'spaRoom',
      'homeOffice',
      'panoramicView',
      'concierge',
      'security',
      'guestParking',
    ],
  },

  {
    name: 'Green Haven Loft',
    description:
      'Situated in the heart of Downtown Dubai, this beautifully designed studio apartment offers a refined living experience within walking distance of world-class landmarks. The interior layout maximizes space with a bright open living area that seamlessly integrates with a modern kitchenette featuring sleek cabinetry and premium finishes. Expansive windows frame iconic views of the surrounding skyline and allow sunlight to illuminate the interior throughout the day. The building offers luxury amenities including a fully equipped fitness center, rooftop pool, and concierge services. Its location places residents minutes away from shopping, fine dining, entertainment venues, and direct access to Dubai Mall and the nearby metro station.',
    address:
      'Boulevard Heights Tower 1, Mohammed Bin Rashid Boulevard, Downtown Dubai',
    city: 'dubai',
    latitude: 25.19482,
    longitude: 55.276657,
    price: 1200000,
    area: 500,
    bedrooms: 1,
    bathrooms: 1,
    images: [
      '/images/properties/b1.jpg',
      '/images/properties/b2.jpg',
      '/images/properties/b3.jpg',
      '/images/properties/b4.jpg',
    ],
    isFeatured: true,
    propertyList: PropertyList.SALE,
    propertyType: 'apartment',
    amenities: [
      'smartHome',
      'gym',
      'jacuzzi',
      'sauna',
      'rooftopTerrace',
      'garage',
      'homeOffice',
      'spaRoom',
      'concierge',
      'security',
      'walkInCloset',
      'panoramicView',
      'bbqArea',
      'guestParking',
      'privatePool',
      'garden',
    ],
  },

  {
    name: 'Skyline Heights',
    description:
      'This spacious four-bedroom family villa is located within the peaceful community of Arabian Ranches and offers a thoughtfully designed layout ideal for modern family living. The ground floor features multiple living areas including a formal lounge, dining room, and a large family room that opens directly onto the landscaped garden and private pool. The kitchen is fully equipped with high-quality appliances and ample storage space. Upstairs, the bedrooms provide privacy and comfort, with the master suite offering a walk-in closet, en-suite bathroom, and balcony views overlooking the community greenery. Residents benefit from access to parks, cycling tracks, golf courses, schools, and community retail centers.',
    address: 'Saheel Villa District 2, Arabian Ranches Community',
    city: 'dubai',
    latitude: 25.052294,
    longitude: 55.268759,
    price: 7800000,
    area: 3500,
    bedrooms: 4,
    bathrooms: 4,
    images: [
      '/images/properties/c1.jpg',
      '/images/properties/c2.jpg',
      '/images/properties/c3.jpg',
      '/images/properties/c4.jpg',
    ],
    isFeatured: false,
    propertyList: PropertyList.SALE,
    propertyType: 'villa',
    amenities: [
      'garden',
      'bbqArea',
      'privatePool',
      'gym',
      'homeOffice',
      'smartHome',
      'garage',
      'driverRoom',
      'maidRoom',
      'outdoorKitchen',
      'panoramicView',
      'walkInCloset',
      'security',
      'guestParking',
      'spaRoom',
      'jacuzzi',
    ],
  },

  {
    name: 'The Modern Elm',
    description:
      'Positioned just steps from the sandy shoreline of Jumeirah Beach Residence, this beautifully appointed three-bedroom apartment delivers a premium coastal lifestyle with panoramic views of the Arabian Gulf. The spacious interior features a modern open-concept design connecting the living, dining, and kitchen areas, making the apartment perfect for both family life and entertaining guests. Floor-to-ceiling glass windows allow natural light to flood the interior while offering spectacular sea views. Residents enjoy access to beachfront dining, luxury retail, and leisure attractions along The Walk.',
    address: 'Rimal 5 Tower, The Walk, Jumeirah Beach Residence',
    city: 'dubai',
    latitude: 25.079287,
    longitude: 55.134388,
    price: 5200000,
    area: 1800,
    bedrooms: 3,
    bathrooms: 3,
    images: [
      '/images/properties/d1.jpg',
      '/images/properties/d2.jpg',
      '/images/properties/d3.jpg',
      '/images/properties/d4.jpg',
    ],
    isFeatured: true,
    propertyList: PropertyList.SALE,
    propertyType: 'apartment',
    amenities: [
      'beachAccess',
      'gym',
      'jacuzzi',
      'sauna',
      'panoramicView',
      'bbqArea',
      'smartHome',
      'garden',
      'garage',
      'spaRoom',
      'concierge',
      'rooftopTerrace',
      'security',
      'guestParking',
      'walkInCloset',
      'homeOffice',
    ],
  },

  {
    name: 'Urban Crest Apartments',
    description:
      'Located in the energetic business district of Business Bay, this contemporary two-bedroom apartment offers modern urban living surrounded by Dubai’s financial and commercial hubs. The apartment features a sleek open-plan living space complemented by a stylish kitchen with modern appliances and elegant finishes. Large windows overlook the Dubai Canal and surrounding skyline. The building includes premium facilities such as a rooftop swimming pool, state-of-the-art fitness center, and 24-hour concierge service.',
    address: 'DAMAC Executive Heights, Al Abraj Street, Business Bay',
    city: 'dubai',
    latitude: 25.186016,
    longitude: 55.268728,
    price: 12000,
    area: 900,
    bedrooms: 2,
    bathrooms: 2,
    images: [
      '/images/properties/e1.jpg',
      '/images/properties/e2.jpg',
      '/images/properties/e3.jpg',
      '/images/properties/e4.jpg',
    ],
    isFeatured: false,
    propertyList: PropertyList.RENT,
    propertyType: 'apartment',
    amenities: [
      'gym',
      'spaRoom',
      'rooftopTerrace',
      'smartHome',
      'jacuzzi',
      'sauna',
      'bbqArea',
      'concierge',
      'security',
      'garage',
      'walkInCloset',
      'guestParking',
      'panoramicView',
      'homeOffice',
      'privatePool',
      'garden',
    ],
  },

  {
    name: 'Willow Park Residences',
    description:
      'This luxurious three-bedroom penthouse on Al Reem Island offers spectacular waterfront views and an elegant contemporary interior. The residence features expansive living spaces with floor-to-ceiling glass walls, allowing natural light to illuminate the interior while showcasing panoramic city and sea views. A designer kitchen with premium appliances anchors the open living area, while each bedroom includes built-in wardrobes and access to private bathrooms. The property also features a private terrace perfect for entertaining.',
    address: 'Gate Tower 2, Al Reem Island Boulevard, Al Reem Island',
    city: 'abu_dhabi',
    latitude: 24.496049,
    longitude: 54.403392,
    price: 8200000,
    area: 1600,
    bedrooms: 3,
    bathrooms: 3,
    images: [
      '/images/properties/f1.jpg',
      '/images/properties/f2.jpg',
      '/images/properties/f3.jpg',
      '/images/properties/f4.jpg',
    ],
    isFeatured: false,
    propertyList: PropertyList.SALE,
    propertyType: 'penthouse',
    amenities: [
      'privatePool',
      'rooftopTerrace',
      'panoramicView',
      'gym',
      'spaRoom',
      'sauna',
      'jacuzzi',
      'garage',
      'smartHome',
      'security',
      'concierge',
      'guestParking',
      'walkInCloset',
      'bbqArea',
      'garden',
      'homeOffice',
    ],
  },

  {
    name: 'The Maple Grove',
    description:
      'Nestled within the peaceful residential district of Khalifa City, this elegant three-bedroom villa combines modern architecture with comfortable family living. The property features spacious indoor living areas complemented by a landscaped outdoor garden and a private swimming pool ideal for relaxing evenings. The kitchen is fully fitted with modern appliances, and the bedrooms are generously sized with built-in wardrobes. Its location offers convenient access to international schools, shopping centers, and major transport routes connecting to central Abu Dhabi.',
    address: 'Street 16, Khalifa City A',
    city: 'abu_dhabi',
    latitude: 24.421421,
    longitude: 54.571427,
    price: 6200000,
    area: 2800,
    bedrooms: 3,
    bathrooms: 3,
    images: [
      '/images/properties/g1.jpg',
      '/images/properties/g2.jpg',
      '/images/properties/g3.jpg',
      '/images/properties/g4.jpg',
    ],
    isFeatured: false,
    propertyList: PropertyList.SALE,
    propertyType: 'villa',
    amenities: [
      'garden',
      'bbqArea',
      'privatePool',
      'smartHome',
      'garage',
      'driverRoom',
      'maidRoom',
      'gym',
      'sauna',
      'spaRoom',
      'security',
      'guestParking',
      'walkInCloset',
      'panoramicView',
      'jacuzzi',
      'homeOffice',
    ],
  },

  {
    name: 'Sunset Boulevard Flats',
    description:
      'Located along the scenic waterfront district of Al Majaz in Sharjah, this stylish studio apartment provides comfortable city living within walking distance of parks, cafés, and shopping destinations. The interior layout maximizes usable space through a clever open design that combines living, dining, and sleeping areas. Residents benefit from views overlooking Khalid Lagoon and convenient access to leisure promenades, cultural attractions, and nearby transport routes connecting to Dubai.',
    address: 'Al Majaz Waterfront Tower, Corniche Road, Al Majaz 2',
    city: 'sharjah',
    latitude: 25.353884,
    longitude: 55.386375,
    price: 7000,
    area: 400,
    bedrooms: 1,
    bathrooms: 1,
    images: [
      '/images/properties/h1.jpg',
      '/images/properties/h2.jpg',
      '/images/properties/h3.jpg',
      '/images/properties/h4.jpg',
    ],
    isFeatured: false,
    propertyList: PropertyList.RENT,
    propertyType: 'apartment',
    amenities: [
      'gym',
      'spaRoom',
      'rooftopTerrace',
      'bbqArea',
      'garden',
      'panoramicView',
      'security',
      'concierge',
      'smartHome',
      'walkInCloset',
      'guestParking',
      'jacuzzi',
      'sauna',
      'garage',
      'homeOffice',
      'privatePool',
    ],
  },

  {
    name: 'Cedar Ridge Retreat',
    description:
      'Situated in the vibrant residential district of Al Nahda Sharjah, this contemporary two-bedroom apartment offers a comfortable living environment for professionals and small families. The property features a spacious living area connected to a modern kitchen with quality cabinetry and appliances. Bedrooms are well proportioned with large windows providing natural light throughout the day. The surrounding community provides easy access to shopping malls, schools, public parks, and major highways connecting to Dubai.',
    address: 'Al Nahda Tower A, Al Nahda Street, Al Nahda',
    city: 'sharjah',
    latitude: 25.289284,
    longitude: 55.367912,
    price: 4800000,
    area: 1100,
    bedrooms: 2,
    bathrooms: 2,
    images: [
      '/images/properties/i1.jpg',
      '/images/properties/i2.jpg',
      '/images/properties/i3.jpg',
      '/images/properties/i4.jpg',
    ],
    isFeatured: false,
    propertyList: PropertyList.SALE,
    propertyType: 'apartment',
    amenities: [
      'gym',
      'spaRoom',
      'bbqArea',
      'smartHome',
      'panoramicView',
      'security',
      'garage',
      'jacuzzi',
      'sauna',
      'rooftopTerrace',
      'guestParking',
      'walkInCloset',
      'homeOffice',
      'privatePool',
      'garden',
      'concierge',
    ],
  },

  {
    name: 'The Horizon Lofts',
    description:
      'Overlooking the iconic waterfront promenade of Abu Dhabi Corniche, this elegant one-bedroom apartment provides a peaceful coastal living environment while remaining close to the city’s vibrant center. The apartment features a comfortable living room with large windows that capture views of the Arabian Gulf and the Corniche skyline. A functional kitchen, modern bathroom, and well-designed bedroom make the residence perfect for singles or couples seeking both comfort and accessibility. The surrounding neighborhood offers beachfront parks, cycling paths, restaurants, and cultural attractions.',
    address: 'Corniche Tower, Corniche Road West, Al Khalidiyah',
    city: 'abu_dhabi',
    latitude: 24.476432,
    longitude: 54.350317,
    price: 9000,
    area: 500,
    bedrooms: 1,
    bathrooms: 1,
    images: [
      '/images/properties/j1.jpg',
      '/images/properties/j2.jpg',
      '/images/properties/j3.jpg',
      '/images/properties/j4.jpg',
    ],
    isFeatured: false,
    propertyList: PropertyList.RENT,
    propertyType: 'apartment',
    amenities: [
      'beachAccess',
      'gym',
      'spaRoom',
      'jacuzzi',
      'sauna',
      'smartHome',
      'panoramicView',
      'bbqArea',
      'rooftopTerrace',
      'security',
      'concierge',
      'garage',
      'walkInCloset',
      'guestParking',
      'garden',
      'homeOffice',
    ],
  },
];
