'use client';

import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { QRCode, QRCodeSvg } from '@/components/ui/qr-code';
import {
  InputOTP,
  InputOTPGroup,
  InputOTPSeparator,
  InputOTPSlot,
} from '@/components/ui/input-otp';
import { REGEXP_ONLY_DIGITS_AND_CHARS } from 'input-otp';
import z from 'zod';
import { Controller, useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { Alert, AlertTitle } from '@/components/ui/alert';
import { LuTriangleAlert } from 'react-icons/lu';
import { authClient } from '@/lib/authClient';
import toast from 'react-hot-toast';
import { cn } from '@/lib/utils';

type QrCodeDialogProps = {
  totpURI: string;
  backupCodes: string[];
  openQrCodeDialog: boolean;
  setOpenQrCodeDialog: (open: boolean) => void;
  hasTwoFactorEnabled: boolean | null | undefined;
  setHasTwoFactorEnabled: (enabled: boolean) => void;
};

const qrCodeSchema = z.object({
  otp: z
    .string({ error: 'OTP is required' })
    .min(6, 'Please enter the 6-digit code'),
});

type QrCodeFormData = z.infer<typeof qrCodeSchema>;

const QrCodeDialog = ({
  totpURI,
  backupCodes,
  openQrCodeDialog,
  setOpenQrCodeDialog,
  hasTwoFactorEnabled,
  setHasTwoFactorEnabled,
}: QrCodeDialogProps) => {
  const form = useForm<QrCodeFormData>({
    resolver: zodResolver(qrCodeSchema),
    defaultValues: {
      otp: '',
    },
    mode: 'onSubmit',
  });

  const onSubmit = async (data: QrCodeFormData) => {
    try {
      const { error } = await authClient.twoFactor.verifyTotp({
        code: data.otp,
      });

      if (error) {
        throw new Error(error.message);
      }
      toast.success('Two-factor authentication enabled successfully');
      setHasTwoFactorEnabled(true);
      setOpenQrCodeDialog(false);
    } catch (error) {
      const errorMessage =
        error instanceof Error ? error.message : 'Something went wrong';
      form.setError('otp', { message: errorMessage });
    }
  };

  const { isSubmitting: isPending } = form.formState;

  return (
    <Dialog open={openQrCodeDialog} onOpenChange={setOpenQrCodeDialog}>
      <DialogContent className='ring-0 rounded-sm pt-0 [&>button:last-child]:hidden sm:max-w-2xl'>
        <form onSubmit={form.handleSubmit(onSubmit)} className='space-y-4'>
          <DialogHeader className='border-b py-3'>
            <DialogTitle className='text-xl font-semibold'>
              Two-factor authentication
            </DialogTitle>
          </DialogHeader>
          {hasTwoFactorEnabled ? (
            <div className='space-y-4'>
              <div className='space-y-1'>
                <p className='text-sm font-semibold'>Backup codes</p>
                <p className='text-muted-foreground text-xs'>
                  Save these codes somewhere safe. Each code can only be used
                  once to sign in if you lose access to your authenticator app.
                </p>
              </div>

              <ul className='grid grid-cols-2 gap-2'>
                {backupCodes.map((code, index) => (
                  <li
                    key={index}
                    className='flex items-center gap-2 rounded-lg border px-3 py-2'
                  >
                    <span className='text-muted-foreground text-[10px] font-medium w-4 shrink-0'>
                      {index + 1}.
                    </span>
                    <span className='font-mono text-sm tracking-widest text-foreground'>
                      {code}
                    </span>
                  </li>
                ))}
              </ul>
            </div>
          ) : (
            <div className='space-y-6'>
              {/* Qr Code  */}
              <QRCode value={totpURI} size={140}>
                <QRCodeSvg />
              </QRCode>
              {/* Explanation Steps list */}
              <ol className='flex flex-col gap-4 list-decimal text-base px-4'>
                <li>
                  Scan this QR code using any authentication application on your
                  device.
                </li>
                <li className='space-y-4'>
                  <p>
                    Enter 6 figure confirmation code generated by the
                    authentication app:
                  </p>
                  {/* OTP input  */}
                  <div className='flex items-center justify-center'>
                    <Controller
                      name='otp'
                      control={form.control}
                      render={({ field }) => (
                        <InputOTP
                          maxLength={6}
                          pattern={REGEXP_ONLY_DIGITS_AND_CHARS}
                          required
                          {...field}
                        >
                          <InputOTPGroup className='gap-2 *:data-[slot=input-otp-slot]:rounded-md *:data-[slot=input-otp-slot]:border'>
                            <InputOTPSlot index={0} className='size-10' />
                            <InputOTPSlot index={1} className='size-10' />
                            <InputOTPSlot index={2} className='size-10' />
                          </InputOTPGroup>
                          <InputOTPSeparator className="[&_svg:not([class*='size-'])]:size-8 text-accent" />
                          <InputOTPGroup className='gap-2 *:data-[slot=input-otp-slot]:rounded-none *:data-[slot=input-otp-slot]:border'>
                            <InputOTPSlot index={3} className='size-10' />
                            <InputOTPSlot index={4} className='size-10' />
                            <InputOTPSlot index={5} className='size-10' />
                          </InputOTPGroup>
                        </InputOTP>
                      )}
                    />
                  </div>
                </li>
              </ol>
              {form.formState.errors.otp && (
                <Alert variant='error'>
                  <LuTriangleAlert />
                  <AlertTitle> {form.formState.errors.otp?.message}</AlertTitle>
                </Alert>
              )}
            </div>
          )}
          <DialogFooter className='px-6 flex flex-row justify-end'>
            <DialogClose
              render={
                <Button
                  variant='secondary'
                  className={cn(
                    hasTwoFactorEnabled && 'bg-green-600 hover:bg-green-700',
                  )}
                >
                  {' '}
                  {hasTwoFactorEnabled ? 'Done' : 'Close'}
                </Button>
              }
            />
            {hasTwoFactorEnabled ? null : (
              <Button type='submit' disabled={isPending}>
                {isPending ? 'Verifying...' : 'Verify'}
              </Button>
            )}
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
};

export default QrCodeDialog;
